version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 8000:80
    privileged: true
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    volumes:
      - ./build/mysql/:/docker-entrypoint-initdb.d
    ports:
      - 4307:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: hogehoge
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
